/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hello.java.server;

public class App {

    public static void main(String[] args) throws Exception {
        ClientServer client = new ClientServer();

        client.start();
    }
}
